// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUhxJrsD6mik9F_fvO3DepiN6q3PlZvj0',
    appId: '1:375123250763:web:52409f6e924eca75cb47ce',
    messagingSenderId: '375123250763',
    projectId: 'pharmacy-icon',
    authDomain: 'pharmacy-icon.firebaseapp.com',
    storageBucket: 'pharmacy-icon.firebasestorage.app',
    measurementId: 'G-F1JJ2Y55M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGQKovrImXQzWLzGFAsZgMU7-EWmpkpF0',
    appId: '1:375123250763:android:39e9d1dbdd2c77fecb47ce',
    messagingSenderId: '375123250763',
    projectId: 'pharmacy-icon',
    storageBucket: 'pharmacy-icon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcxIEOofhFjhP4YpK19TZ-wm6vvu1LUpE',
    appId: '1:375123250763:ios:296958590a713233cb47ce',
    messagingSenderId: '375123250763',
    projectId: 'pharmacy-icon',
    storageBucket: 'pharmacy-icon.firebasestorage.app',
    androidClientId: '375123250763-6hh941c35dfiq0i4momlq64qrsk37604.apps.googleusercontent.com',
    iosClientId: '375123250763-o9nlg2mut8dkp2jfl0mdoqf16udc4u9a.apps.googleusercontent.com',
    iosBundleId: 'com.pharmacy.icontech.app.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcxIEOofhFjhP4YpK19TZ-wm6vvu1LUpE',
    appId: '1:375123250763:ios:296958590a713233cb47ce',
    messagingSenderId: '375123250763',
    projectId: 'pharmacy-icon',
    storageBucket: 'pharmacy-icon.firebasestorage.app',
    androidClientId: '375123250763-6hh941c35dfiq0i4momlq64qrsk37604.apps.googleusercontent.com',
    iosClientId: '375123250763-o9nlg2mut8dkp2jfl0mdoqf16udc4u9a.apps.googleusercontent.com',
    iosBundleId: 'com.pharmacy.icontech.app.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUhxJrsD6mik9F_fvO3DepiN6q3PlZvj0',
    appId: '1:375123250763:web:52409f6e924eca75cb47ce',
    messagingSenderId: '375123250763',
    projectId: 'pharmacy-icon',
    authDomain: 'pharmacy-icon.firebaseapp.com',
    storageBucket: 'pharmacy-icon.firebasestorage.app',
    measurementId: 'G-F1JJ2Y55M2',
  );
}
